//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public BloodGroup()
        {
            this.BloodBags = new HashSet<BloodBag>();
            this.Donors = new HashSet<Donor>();
        }
    
        public string title { get; set; }
        public int quantity { get; set; }
        public int NoOfDonors { get; set; }
        public int branchId { get; set; }
    
        public virtual ICollection<BloodBag> BloodBags { get; set; }
        public virtual ICollection<Donor> Donors { get; set; }
    }
}
