//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Donors = new HashSet<Donor>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int branchID { get; set; }
        [DisplayName("Title :")]
        [Required]
        public string title { get; set; }
        public string managerID { get; set; }
        public string labAssistantID { get; set; }
        public int registeredDonors { get; set; }

        [DisplayName("Location :")]
        [Required]
        public string location { get; set; }
        [DisplayName("City :")]
        [Required]
        public string city { get; set; }
    
        public virtual ICollection<Donor> Donors { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
