//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationLog
    {
        public int requestID { get; set; }
        public System.DateTime supplyDate { get; set; }
        public int branchID { get; set; }
        public string bloodGroup { get; set; }
        public int quantity { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
