//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int donorID { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string gender { get; set; }
        public int branchID { get; set; }
        public string bloodGroup { get; set; }
        public int regFormID { get; set; }
        public string contactNo { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string cnic { get; set; }
        public Nullable<System.DateTime> lastDonationTime { get; set; }
        public int totalDonations { get; set; }
        public string PicPath { get; set; }
    
        public virtual BloodGroup BloodGroup1 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual RegForm RegForm { get; set; }
    }
}
