//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Employee
    {
        public string empID { get; set; }

        [DisplayName("Name :")]
        [Required]
        public string empName { get; set; }


        public string gender { get; set; }

        [DisplayName("Gender :")]
        [Required]
        public SelectList GenderList { get; set; }

        [DisplayName("D.O.B :")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }

        [DisplayName("Joining Date :")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime joiningDate { get; set; }

        [DisplayName("Contact No. :")]
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string contactNo { get; set; }

        [DisplayName("Salary :")]
        [Required]
        public int salary { get; set; }
        public int branchID { get; set; }

        [DisplayName("Job :")]
        [Required]
        public string job { get; set; }

        [DisplayName("Address :")]
        [Required]
        public string address { get; set; }

        [DisplayName("City :")]
        [Required]
        public string city { get; set; }
    
        public virtual Branch Branch { get; set; }

        public Employee()
        {
            List<SelectListItem> gender = new List<SelectListItem>();
            gender.Add(new SelectListItem { Text = "Male", Value = "Male" });
            gender.Add(new SelectListItem { Text = "Female", Value = "Female" });

            this.GenderList = new SelectList(gender, "Value", "Text");

        }
    }
}
