//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepient
    {
        public Recepient()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int recepientID { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string contact { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
