//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegForm
    {
        public RegForm()
        {
            this.Donors = new HashSet<Donor>();
        }
    
        public int formID { get; set; }
        public string name { get; set; }
        public System.DateTime DOB { get; set; }
        public string gender { get; set; }
        public int branchID { get; set; }
        public string bloodGroup { get; set; }
        public string contactNo { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string formStatus { get; set; }
        public string cnic { get; set; }
        public string PicPath { get; set; }

        public virtual ICollection<Donor> Donors { get; set; }
    }
}
