//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int requestID { get; set; }
        public string reqBloodGroup { get; set; }
        public int recepientID { get; set; }
        public int reqQuantity { get; set; }
        public int reqStatus { get; set; }
        public Nullable<System.DateTime> supplyDate { get; set; }
        public System.DateTime requestDate { get; set; }
        public System.DateTime requiredDate { get; set; }
        public string location { get; set; }
        public string city { get; set; }
    
        public virtual DonationLog DonationLog { get; set; }
        public virtual Recepient Recepient { get; set; }
    }
}
